const Map<String, String> appStringsEn = {
  'appName': 'PhrasePal',
  'appTagline': 'Offline travel phrases',
  'loading': 'Loading…',
  'skipOnboard': 'Skip',
  'next': 'Next',
  'getStarted': 'Get started',
  'onboardTitle1': 'Phrases + audio, bundled',
  'onboardDesc1': 'Useful lines for airport, hotel, food, shopping and emergencies — with playback on this device.',
  'onboardTitle2': 'No mic. No location. No account.',
  'onboardDesc2': 'PhrasePal never asks for the microphone or GPS. Everything you need is already in the app.',
  'onboardTitle3': 'Works anywhere',
  'onboardDesc3': '100% offline after install. One-hand lists, stars, and quick practice.',
  'navHome': 'Phrases',
  'navSaved': 'Saved',
  'navShop': 'Shop',
  'navSettings': 'Settings',
  'pickSituation': 'Pick a situation',
  'language': 'Language',
  'japanese': 'Japanese',
  'catAirport': 'At the Airport',
  'catHotel': 'Hotel',
  'catFood': 'Food',
  'catShopping': 'Shopping',
  'catEmergency': 'Emergency',
  'catTransport': 'Transport',
  'catHealth': 'Health',
  'catNumbers': 'Numbers & directions',
  'playAll': 'Play audio',
  'playAllDesc': 'Play all phrases in this category',
  'savedPhrases': 'Saved Phrases',
  'travelStreak': 'Travel Streak',
  'days': '{n} Days',
  'offlineBanner': '100% Offline',
  'offlineBannerDesc': 'All phrases and audio available offline',
  'yourFavorites': 'Your favorites',
  'quickPractice': 'Quick Practice',
  'quickPracticeDesc': 'Review your saved phrases',
  'startPractice': 'Start Practice',
  'noFavorites': 'Star phrases to practice later.',
  'practiceTitle': 'Practice',
  'practiceDone': 'Nice work',
  'practiceScore': '{ok} / {total} correct',
  'lockedLanguage': 'Unlock this language in the shop',
  'slowAudio': 'Slow audio',
  'settings': 'Settings',
  'appearance': 'Look',
  'currentLook': 'Current look',
  'resetDefault': 'Reset to default',
  'resetDefaultDesc': 'Theme, background and card skin',
  'lookResetDone': 'Default look restored',
  'darkMode': 'Dark mode',
  'privacyPolicy': 'Privacy policy',
  'privacyPolicyBody':
      'PhrasePal is an offline travel phrasebook. Phrases and playback stay on this device. We do not use a microphone, location, or an account. Optional Google Play purchases buy stars or remove ads. A small config file only checks whether store billing should stay on. If that check fails (network, timeout, or error), the last known setting is used.',
  'restorePurchases': 'Restore purchases',
  'shop': 'Shop',
  'shopMenuThemes': 'Themes',
  'shopMenuBackgrounds': 'Backgrounds',
  'shopMenuSkins': 'Skins',
  'shopMenuFeatures': 'Features',
  'shopThemeDefault': 'Harbor navy',
  'shopThemeDefaultDesc': 'Cream paper and navy type',
  'shopThemeSakura': 'Sakura',
  'shopThemeSakuraDesc': 'Soft pink travel cards',
  'shopThemeGold': 'Temple gold',
  'shopThemeGoldDesc': 'Warm gold accents',
  'shopThemeMidnight': 'Night train',
  'shopThemeMidnightDesc': 'Deep blue evening look',
  'shopBgDefault': 'Washi cream',
  'shopBgDefaultDesc': 'Quiet paper background',
  'shopBgFuji': 'Fuji dawn',
  'shopBgFujiDesc': 'Mountain wash behind lists',
  'shopBgWashi': 'Indigo wash',
  'shopBgWashiDesc': 'Ink-wash gradient',
  'shopBgDusk': 'Lantern dusk',
  'shopBgDuskDesc': 'Warm evening gradient',
  'shopSkinDefault': 'Standard cards',
  'shopSkinDefaultDesc': 'Clean rounded cards',
  'shopSkinSoft': 'Soft glass',
  'shopSkinSoftDesc': 'Frosted phrase cards',
  'shopSkinInk': 'Ink outline',
  'shopSkinInkDesc': 'Strong navy borders',
  'shopRemoveAds': 'Remove ads',
  'shopRemoveAdsDesc': 'Hide the home promo box (one-time)',
  'shopFeatDoubleCoins': 'Double stars',
  'shopFeatDoubleCoinsDesc': 'Earn twice the stars from daily and practice',
  'shopFeatSlowAudio': 'Slow playback',
  'shopFeatSlowAudioDesc': 'Hear each line more slowly',
  'shopFeatLargeType': 'Large type',
  'shopFeatLargeTypeDesc': 'Bigger native script on cards',
  'shopFeatExtraCats': 'Extra situations',
  'shopFeatExtraCatsDesc': 'Transport, health, numbers',
  'shopFeatQuizPlus': 'Practice plus',
  'shopFeatQuizPlusDesc': 'More questions in a session',
  'shopLangKo': 'Korean pack',
  'shopLangKoDesc': 'Korean phrases + audio',
  'shopLangTh': 'Thai pack',
  'shopLangThDesc': 'Thai phrases + audio',
  'shopLangIt': 'Italian pack',
  'shopLangItDesc': 'Italian phrases + audio',
  'shopLangDe': 'German pack',
  'shopLangDeDesc': 'German phrases + audio',
  'shopLangZh': 'Chinese pack',
  'shopLangZhDesc': 'Chinese phrases + audio',
  'apply': 'Apply',
  'applied': 'Applied',
  'resetToDefault': 'Default',
  'buy': 'Unlock',
  'owned': 'Owned',
  'insufficientCoins': 'Need more stars',
  'purchaseFailed': 'Purchase failed',
  'purchaseSuccess': 'Unlocked in PhrasePal',
  'alreadyOwned': 'Already owned',
  'coinsAdded': 'Stars added',
  'coinsAddedWithBonus': 'Stars added with bonus',
  'coinEarned': '+{amount} stars',
  'coinRewardSub': 'You now have {balance} stars',
  'removeAdsUnlocked': 'Ads removed',
  'dailyRewardClaimed': 'Daily stars claimed',
  'spinRewardEarned': 'Wheel reward',
  'levelRewardEarned': 'Practice stars',
  'favoriteRewardEarned': 'Starred a phrase',
  'shopClaimDaily': 'Claim',
  'shopClaimedDaily': 'Claimed today',
  'shopDailyReward': 'Daily stars',
  'shopDailyRewardDesc': 'Come back each day',
  'buyStars': 'Get stars',
  'buyWithGooglePlay': 'Google Play',
  'coinPack': 'Pack {num}',
  'openingBilling': 'Opening Google Play…',
  'billingDisabled': 'Store billing is off. You can still spend stars in the shop.',
  'configTimeout': 'Could not reach the shop config (timeout). Using the last known setting.',
  'configNetwork': 'No connection for shop config. Using the last known setting.',
  'adPlaceholder': 'Ad',
  'adPromo': 'Need more stars? Open a pack.',
  'mtwtfss': 'M T W T F S S',
  'correct': 'Correct',
  'wrong': 'Not quite',
  'hearAgain': 'Hear again',
  'continue': 'Continue',
  'english': 'English',
  'about': 'About',
  'version': 'Version {v}',
  'useDefault': 'Use default',
  'shopToday': 'Today',
  'dailyClaimed': 'Done',
  'claimDaily': 'Claim',
  'shopPacks': 'Star packs',
  'active': 'Active',
  'unlocked': 'Owned',
  'promoCompactTitle': 'Weekly star deal',
  'promoHotDeal': 'Hot deal',
  'promoHotDealDesc': 'Pack {num} includes extra stars this week.',
  'promoBuyShort': 'Buy',
  'promoBuyNow': 'Buy now',
  'firstPurchaseBadge': 'First buy bonus',
  'promoUnlockReady': 'You can unlock something now',
  'promoUnlockRemaining': '{count} stars to the next unlock',
  'purchasePromoDesc': '{coins} stars for this pack',
  'getMorePoints': 'Get stars',
  'insufficientCoinsDetail': 'You need {need} more stars.',
  'earnCoins': 'Earn stars',
  'earnCoinsDesc': 'Daily login, practice, and starring phrases.',
  'dailyReward': 'Daily stars',
  'loginStreak': '{days}-day streak',
  'spinWheel': 'Lucky spin',
  'spinNow': 'Spin',
  'spinUsed': 'Spun today',
  'buyCoins': 'Buy stars',
  'buyCoinsDesc': '10 packs via Google Play. Consumable.',
  'configNetworkError': 'Could not reach shop config. Using last known setting.',
  'billingUnavailable': 'Google Play billing is not available on this device.',
  'productsNotFound': 'Star packs are not in the store yet.',
  'earnCoinsHint': 'Or earn stars by practicing and a daily claim.',
  'coinBalanceLabel': 'Your stars',
  'hotDealBadge': 'Hot',
  'bestValueBadge': 'Best',
  'coinBonusExtra': '{base} + {bonus} bonus',
  'privacyPolicyTitle': 'Privacy',
  'audioError': 'Could not play this phrase. Check volume, or try on a real phone — the emulator often has no sound.',
  'statsNotes': '{n} phrases saved',
};
